### ISSUE TITLE
Discord deprecating older API version

### ISSUE THREAD

**Issue by synsypa** [zhangchuck/discord_quote_bot#10]
> This email is to let you know about some changes to our APIs. Specifically, we have released documentation on API and Gateway v6 and have deprecated all older versions (3, 4, and 5). These older versions will be discontinued on October 16, 2017.
> 
> With this date, the default API version will be changing from v3 to v6. We have also recently documented our API versioning, so we recommend you start specifying a version in API requests to prevent future updates from breaking your application.
> 
> To ensure your application is up to date, please check out our change log to see a list of breaking changes to our APIs. Most third-party Discord libraries are already on v6, so make sure you upgrade to the latest version available if you use one.
> 
> Stay awesome!
> 
> — Discord Dev Team

should make sure we're up to date

**Comment by zhangchuck** [comment]
This can probably be closed since the bot is working?
