### ISSUE TITLE
Improve !quote by using a PR

### ISSUE THREAD

**Issue by zhangchuck** [zhangchuck/discord_quote_bot#21]
# Description

Improve !quote functionality by:

- [ ] ~~Including the reference username (rather than the text rusername). e.g., quote `@synsypa` rather than `synsypa`~~
- [x] Handle quoting quote-bot differently than quoting anything else. (#22 )
- [ ] Use spoiler gates to handle long quotes of quotes
- [x] Make times display on quotes better (we'll fix this if we can get to #34, still under development in the augmented conversations branch)

@synsypa @DoubleSec

# Examples

Place the earliest quoted text below in a spoiler gate.

![image](https://user-images.githubusercontent.com/4514597/52661418-dc82dc80-2eb6-11e9-9b9d-c655b8172d8d.png)

This should quote cz, note quotebot.
![image](https://user-images.githubusercontent.com/4514597/52661537-223fa500-2eb7-11e9-8ffa-11ec0cf0bf3b.png)

**Comment by DoubleSec** [comment]
I think before we made an explicit decision to not use @ mentions for normal quotes, so as to not spam notifications.

**Comment by zhangchuck** [comment]
- I must have forgotten about that design decision, but probably still a good idea to keep i this way. 
- Should this still be the case for quotes with a reply?
- One other alternative might be able to edit in the mentions after sending the message. I think we tested that once and it does not trigger notifications. (highlights the line though)
- I'm probably going to leave the `mention` in the log file since it's a better identifier (although maybe should log the actual UUID/Snowflake).

**Comment by zhangchuck** [comment]
- Going to get rid of the mentions, makes quoting quotes terrible
- Coloring guide: https://pastebin.com/jGvqPxnT

**Comment by zhangchuck** [comment]
For reference, @DoubleSec comments on quoting a quote:

![image](https://user-images.githubusercontent.com/4514597/52829905-76978000-3083-11e9-87a4-b4dcb7428553.png)
