### ISSUE TITLE
Why is AZ being ignored?

### ISSUE THREAD

**Issue by zhangchuck** [zhangchuck/discord_quote_bot#23]
AZ/nobody can do this:

~~!quote 543874809747210240 Kevin wonders if he should search "Drakes fucking cars..."~~

```
!quote 543874809747210240 *Kevin wonders if he should search "Drakes fucking cars..."*
!quote 543874809747210240 **Kevin wonders if he should search "Drakes fucking cars..."**
```

but everyone else can.

Original message is: synsypa [2019-02-09 19:24:19] said: 

@DoubleSec Can you add the text that you typed in.

**Comment by zhangchuck** [comment]
These are the requests that are broken:

```
!quote 543874809747210240 *Kevin wonders if he should search "Drakes fucking cars..."*
!quote 543874809747210240 **Kevin wonders if he should search "Drakes fucking cars..."**
```
are both broken for me as well.

**Comment by zhangchuck** [comment]
Some stuff that got tried:

![image](https://user-images.githubusercontent.com/4514597/52663648-f115a380-2ebb-11e9-8f97-818dc4d15a8e.png)

**Comment by KingXiaoDi** [comment]
Seems to have trouble with quotation marks inside of the user's reply. E.g.

**__FAILS (see 2nd to last line in screenshot):__** !quote 543874809747210240 \**Kevin wonders if he should search "Drakes fucking cars..."\**
**__Quotes, but drops the quotation marks (see last line in screenshot):__\** !quote 543874809747210240 **Kevin wonders if he should search "Drakes fucking cars...\**"

**Comment by KingXiaoDi** [comment]
![github](https://user-images.githubusercontent.com/20346688/59645560-84980300-9140-11e9-97ba-e7251dc87d3d.PNG)
Further development in quoting punctuation marks. There are different types of single quotes. The bot ignores messages containing the former, but properly parses messages containing the latter. 

(Feel free to split off into its own issue)

**Comment by zhangchuck** [comment]
May be relevant? https://github.com/Rapptz/discord.py/issues/1032

**Comment by zhangchuck** [comment]
Okay, discord.py is using `"` to denote strings that should be handled together (default behavior is to split on spaces). We infer this from the behavior here. Using the double-quotes means that the command is parsed with the additional string ("death")  as part of `msg_id` instead of as part of `reply`.

![image](https://user-images.githubusercontent.com/4514597/64296334-b8f1b300-cf28-11e9-9d2c-4e19fd101fd4.png)
