### ISSUE TITLE
Rework quotes by using EMBEDs

### ISSUE THREAD

**Issue by zhangchuck** [zhangchuck/discord_quote_bot#26]
# Description

Rework the quotes so that we get even nicer looking quotes via the `embed`s

# References

- https://anidiots.guide/first-bot/using-embeds-in-messages
- https://leovoel.github.io/embed-visualizer/
- https://discordpy.readthedocs.io/en/latest/api.html#embed

# Example

This is an embed. Looks much prettier.

![image](https://user-images.githubusercontent.com/4514597/52672710-79ec0980-2ed3-11e9-9fd4-8d2a27c941e7.png)

**Comment by DoubleSec** [comment]
Absolutely not. I have embeds off for very principled reasons and I'm not turning them back on.

**Comment by synsypa** [comment]
+1 to AZ, embeds are terrible

**Comment by zhangchuck** [comment]
We don't need full embeds to get better formatting, we'll use the backwards-compatible (i.e., no link preview needed) version of embeds as outlined in #34.
