### ISSUE TITLE
Create a quote-bot-beta to facilitate testing new features

### ISSUE THREAD

**Issue by zhangchuck** [zhangchuck/discord_quote_bot#27]
# Description

To facilitate testing, it would be nice for the `#test` channel to be assigned to have a version of quote-bot that is based off of a different branch (e.g., `discord_quote_bot:development` or `discord_quote_bot:test`).

(Might also be useful to re-familiarize/learn Docker)

# Concrete tasks

- [x] Create a new branch ~~`testing`~~ `development`
    - new feature branches should merge to ~~`testing`~~ `development` (indiscriminately)
    - PRs should be required for merging from ~~`testing`~~ `development` to `master`
- [x] ~~Create a [separate dockerfile](https://hub.docker.com/r/cyzhang/discord_quote_bot/dockerfile)/docker image that pulls from the `development` branch instead of `master`~~
    - This isn't necessary. Docker already can build multiple branches, and we can just tell the machine hosting the bot to grab the `development` tag from docker hub.
- [x] Integrate the `development` branch with Docker Hub~~with the separate docker image~~. Make sure that DockerHub rebuilds the image with the `development` tag every time there is a new change to `development` branch on GitHub
   - Might need to revisit the [GitHub/Docker integration](https://github.com/zhangchuck/discord_quote_bot/settings/installations), looks like the old way works but is deprecated
- [x] Create a new `quote-bot-testing` or `quote-bot-beta`
   - [x] Get a new set of a credentials
   - [x] Change the secret keys in the Docker Hub config to reflect the new bot
   - [ ] Other hookup tasks? @synsypa probably knows best here
   - [x] Need to figure out some way to isolate `quote-bot` and `quote-bot-beta` so that `!` only triggers calls to one of them. Maybe some way to kick `quote-bot-beta` out of all channels except for `#test`?
- [x] Make sure auto-deploy is working so we need fewer manual interventions
    - Either watchtower or https://medium.com/@iaincollins/docker-swarm-automated-deployment-cb477767dfcf

**Comment by DoubleSec** [comment]
I think we're growing too fast. Time to get lean again and focus on our strengths.

**Comment by synsypa** [comment]
* Maybe some way to kick `quote-bot-beta` out of all channels except for `#test`? 

this is easy, i can just assign it a new role `bot-testing` and only allow that role to access `#test`

**Comment by zhangchuck** [comment]
Did as you suggested here, I kicked the `bot` role out of #test and created a `bot-development` role that has only been added to #test.

**Comment by synsypa** [comment]
I think this is completed now with quote-bot-dev
