### ISSUE TITLE
quoting code blocks breaks really bad

### ISSUE THREAD

**Issue by synsypa** [zhangchuck/discord_quote_bot#38]
<img width="850" alt="screen shot 2019-02-27 at 5 51 42 pm" src="https://user-images.githubusercontent.com/6685753/53535644-6b4b4800-3ab8-11e9-87bd-317b5eaf9007.png">

not ideal

**Comment by zhangchuck** [comment]
Seems like the fixes in #39, which ave made it to development will fix this by switching our quote-formatting to blockquotes (instead of code blocks). New version looks much better now: 

![image](https://user-images.githubusercontent.com/4514597/64294763-70d09180-cf24-11e9-9f90-3595cc7e864b.png)

**Comment by zhangchuck** [comment]
Fixed in #42.
