### ISSUE TITLE
Replace "ujson" with "json" package

### ISSUE THREAD

**Issue by zhangchuck** [zhangchuck/discord_quote_bot#9]
- We don't need the performance bump from `ujson`
- It makes it a lot easier to build the container if we just use `json`, which is included in base python
- It shouldn't be hard to replace (but we need to double check), since the function is only used once and json.loads should be a drop in replacement for ujson.loads.

STEPS:
1. Check if json/ujson are drop-in replacements for each other
2. Edit `discord_quote.py` so that we use just `json`
3. Remove the `import ujson` line
4. Remove `ujson` from `requirements.txt`
5. Remove `gcc` from the list of packages to install in `Dockerfile`

@synsypa

**Comment by synsypa** [comment]
done
